baseURL: "https://tautastic.github.io/codespace/"
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production
  keywords: [ Blog, Portfolio, Coding ]
  author: Ahmed Sami
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  mainSections:
    - categories

  fuseOpts:
    isCaseSensitive: false
    shouldSort: false
    location: 0
    distance: 500
    threshold: 0.1
    minMatchCharLength: 2
    keys: [ "title", "permalink", "summary", "content" ]

  assets:
    disableHLJS: false
    disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

outputs:
  home:
    - HTML
    - JSON

defaultContentLang: en

languages:
  en:
    contentDir: content/en
    languageName: "English"
    DateFormat: "January 2, 2006"
    title: Ahmed's CodeSpace
    weight: 1
    taxonomies:
      tag: tags
    menu:
      main:
        - name: Search
          url: search
          weight: 5
        - name: Categories
          url: categories
          weight: 10
        - name: Tags
          url: tags
          weight: 15
        - name: Archive
          url: archives
          weight: 20
    homeInfoParams:
      Title: "Ahmed's CodeSpace"
      Content: >
        Welcome to Ahmed's CodeSpace.

        - On this page I share what I know about various **[topics](categories/)**.
    socialIcons:
      - name: github
        url: "https://github.com/tautastic"

  de:
    contentDir: content/de
    languageName: "German"
    DateFormat: "2 January, 2006"
    title: Ahmeds CodeSpace
    weight: 2
    taxonomies:
      tag: tags
    menu:
      main:
        - name: Suchen
          url: search
          weight: 5
        - name: Kategorien
          url: categories
          weight: 10
        - name: Tags
          url: tags
          weight: 15
        - name: Archiv
          url: archives
          weight: 20
    homeInfoParams:
      Title: "Ahmeds CodeSpace"
      Content: >
        Willkommen zu Ahmeds CodeSpace.

        - Auf dieser Seite teile ich mein Wissen zu verschiedenen **[Themen](categories/)**.
    socialIcons:
      - name: github
        url: "https://github.com/tautastic"


markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
